### ISSUE TITLE
Don't always create and initialize a new database on build

### ISSUE THREAD

**Issue by FraserThompson** [bitnami/bitnami-docker-phpbb#44]
My workflow for devving on docker-compose is to make changes and then run docker-compose up --build -d to build those changes into the running container. For production I would also use this workflow to deploy changes. 

In every other Docker container this will simply rebuild the container and reconnect to the existing database table. But in bitnami-docker-phpbb it wants to initialize a new database table each time with a randomly generated suffix. 

Instead I would like to be able to make it initialize a table only once. A possible interface for this would be to supply it with a database name on an environment variable like MARIADB_DATABASE. If it exists then it should assume it's been initialized already and just connect to it.

**Comment by chipironcin** [comment]
Hi @FraserThompson 
There are several bits around this topic.

bitnami-docker-phpbb will initialize on startup if there is no volume with persisted data.
You can tell bitnami-docker-php which MariaDB server to use, thanks to some env variables (https://github.com/bitnami/bitnami-docker-phpbb#environment-variables)

bitnami-docker-phpbb cannot assume it is already configured only by connecting to an existing database, it also needs some initialized and configured files.

If you want to persist your data between docker-compose runs, read this section about mounting volumes in the docker-compose file:
https://github.com/bitnami/bitnami-docker-phpbb#mount-host-directories-as-data-volumes-with-docker-compose

If the volumes are empty (first run), phpbb will initialize. Next runs, it will detect data has been already initialized and just start the application.
Would that solve your issue?

**Comment by FraserThompson** [comment]
Okay then this might be a bug. I'll explain my situation with more detail since possibly my usage is slightly non-standard.

I'm using my own Dockerfile inherited from bitnami-phpbb simply to make adding my own style easier. This is the contents of that Dockerfile:

```
FROM bitnami/phpbb:3.2.0-r6
COPY ["phpbb", "/opt/bitnami/phpbb"]
```

My docker-compose file builds this image.

I'm also using the official MySQL image and persisting the database by mounting /var/lib/mysql as a named data volume. 

I run `docker-compose up --build -d` and it brings up the bitnami PHPBB container and the MySQL container. I wait for bitnami to initialize.

Then I make a change so Docker will rebuild and run `docker-compose up --build -d`. It rebuilds the image, brings the containers up and initializes another different database. If I run `SHOW databases;` I can see that there's the original `bitnami_phpbb` database but also a new `bitnami_phpbb_B6wAF` database.

If I do this same process again it'll initialize another one. 

So it seems like it isn't detecting the existing database correctly. What method does it use to determine whether the database exists and is populated?

**Comment by prydonius** [comment]
@FraserThompson Are you mounting a volume at `/bitnami` to persist the phpbb config? The container will use this volume to check if it needs to initialize a new database or not. I'm not sure what effect this will have given you're overwriting `/opt/bitnami/phpbb` with your development code.

Out of curiosity, couldn't you just mount `/bitnami` to a local dir and develop phpbb there?

**Comment by FraserThompson** [comment]
I wanted to make the container as 'throwaway' as possible by persisting only exactly what I need persisted so I was only persisting /bitnami/phpbb in a volume. I don't understand why the apache config at /bitnami/apache or php config at /bitnami/php needed to be persisted for things to work, but it looks like mounting /bitnami fixed the issue for me.

If I'm understanding correctly the database and phpBB container are strongly coupled... If the /bitnami volume gets lost somehow, or if I want to migrate my database to a remote host, it'd break the phpBB container because of the way config.php is automagically generated, right?

Sidenote: I kind of wish there was some more documentation on the file structure and inner workings so it didn't have to be deduced by poking around.

**Comment by chipironcin** [comment]
Yes @FraserThompson, I agree with your suggestion about more documentation on the file structure. Thank you for the tip, we will take it into account!

Regarding the storage and volumes:
  - The docker-compose file mounts the named volume `phpbb_data` to `/bitnami` inside the phpBB container
  - The docker-compose file mounts the named volume `mariadb_data` to `/bitnami` inside the MariaDB container
  - phpBB store its data in `/bitnami/phpbb` inside the phpBB container
  - Apache store its data in `/bitnami/phpbb` inside the phpBB container
  - MariaDB store its data in `/bitnami/mariadb` inside the MariaDB container

The Bitnami phpBB Docker image should be compatible with the official MySQL/MariaDB Docker image by providing the right parameters (see https://github.com/bitnami/bitnami-docker-phpbb#environment-variables)

If you delete the `phpbb_data` named volume, the Bitnami phpBB Docker container will try to initialize phpBB from scratch at startup, creating the new databases, files and configuration for the application.

If you want to migrate your database to a remote host, you will need to make a backup of the database data and restore it in the new database server. In case of migrating to another Bitnami MariaDB container, just mount the `mariadb_data` named volume into the new container. In case of using the official container, follow this guide to connect the folder `data` inside the `mariadb_data` named volume to the new image as the `data` volume.

https://github.com/docker-library/docs/tree/master/mariadb#where-to-store-data
