### ISSUE TITLE
Members IP

### ISSUE THREAD

**Issue by wallforfry** [bitnami/bitnami-docker-phpbb#46]
Hi is there a way to know members ip ? Actually all members had the same ip which is the containeur ip

**Comment by jotadrilo** [comment]
Hi @wallforfry,

Could you describe the mechanism you are using to figure the members' IP out?
Example, from Apache `access_log` file:

Executing this from the container host (the machine where the container is running):
```
> curl -L localhost
```
Produces:
```
172.19.0.1 - - [28/Jul/2017:14:09:41 +0000] "GET / HTTP/1.1" 200 13365
```

Executing this from the container itself:
```
> curl -L localhost
```
Produces:
```
127.0.0.1 - - [28/Jul/2017:14:11:14 +0000] "GET / HTTP/1.1" 200 13359
```

Accessing the application from an external machine:
```
172.17.0.3 - - [28/Jul/2017:14:11:47 +0000] "GET / HTTP/1.1" 200 3548
```

Accessing the application from another external machine:
```
172.17.0.6 - - [28/Jul/2017:14:21:44 +0000] "GET / HTTP/1.1" 200 3502
```
