### ISSUE TITLE
Styles/Themes folder

### ISSUE THREAD

**Issue by ADRFranklin** [bitnami/bitnami-docker-phpbb#52]
Hi,

After recently learning about docker, I decided to make my forum dockerized. So I found this image and so far it works really well and I love it. 

However I came across an issue where you don't seem to link to the themes/styles folder so you can't manually upload a theme.

I know the alternative is to create a separate volume pointing directly to the folder or create a symblink inside the bitnami folder. I thought I should maybe mention this as it seems like maybe an oversight.

I am surprised no one has made an issue before, I would think forum Styles were a common thing people do with forums (atleast for me).

**Comment by tompizmor** [comment]
Hello @ADRFranklin,

You're right! I think the styles folder should also be persisted. We will take it into account for future releases of the phpBB docker image. 
We will update this issue once the new image is released.

**Comment by tompizmor** [comment]
Hi @ADRFranklin,

We have added the `styles` folder to the list of persisted directories in the latest version of the phpBB docker image.

**Comment by ADRFranklin** [comment]
Okay, perfect. Will use the latest version now. Thank you.
