### ISSUE TITLE
Persist "language" directory

### ISSUE THREAD

**Issue by herver** [bitnami/bitnami-docker-phpbb#53]
**Description**

I'd like to have multiple languages on my bitnami-based phpBB forum. Unfortunately, it seems like the `language`" folder is not set to be stored on the persistent volume by default:

```
lrwxrwxrwx  1 root   root       20 Dec 30 09:15 store -> /bitnami/phpbb/store
lrwxrwxrwx  1 root   root       20 Dec 30 09:15 files -> /bitnami/phpbb/files
lrwxrwxrwx  1 root   root       21 Dec 30 09:15 images -> /bitnami/phpbb/images
lrwxrwxrwx  1 root   root       25 Dec 30 09:15 config.php -> /bitnami/phpbb/config.php
lrwxrwxrwx  1 root   root       18 Dec 30 09:15 ext -> /bitnami/phpbb/ext
lrwxrwxrwx  1 root   root       21 Dec 30 09:15 styles -> /bitnami/phpbb/styles
```

It would be nice to have the `language` folder being a symlink to `/bitnami/phpbb/languages`

**Version**
Running `phpbb` on k8s (on prem) via Helm (chart version `phpbb-4.0.0, app version: `3.2.4)

**Comment by andresbono** [comment]
Hi @herver, thanks for submitting this issue. We can include the change that you are proposing in future releases of the container image.

In the meantime, you can create a specific volume for the languages folder apart from the one that is  storing `/bitnami/phpbb`.

Hope it helps!

**Comment by herver** [comment]
Hi @andresbono,

I did this exact workaround for the time being, but thought it might be useful for others to have it out of the box !

Cheers !

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we are currently releasing a new version of the container that does persist the language folder. I will write again as soon as it is out

**Comment by javsalgar** [comment]
Hi,

It is now out. https://github.com/bitnami/bitnami-docker-phpbb/commit/a599063ac075daf5f3fb2658f33d2c4dee30e39a

If you find any issues with the persistence of this folder, do not hesitate to reopen this ticket
