### ISSUE TITLE
HTTP 404 for ajax.js and fn_forum.js due to incorrect phpbb url path

### ISSUE THREAD

**Issue by marcelothomaz** [bitnami/bitnami-docker-phpbb#54]
**Description**

HTTP 404 on ajax.js and fn_forum.js due to wrong url used by INCLUDEJS

**Steps to reproduce the issue:**

1. Follow instructions and create a new container using the docker-compose file
2. Login and open developer tools in your chosen browser
3. Notice 404 errors on fn_forum.js and ajax.js.

URL is /bitnami/phpbb/template/... while it should be starting on the /template

**Describe the results you expected:**

It should be expected no 404 errors and correct load of those two files.
phpBB URL should be on the root / not /bitnami/phpbb

This looks like a manual install and providing the base path as /bitnami/phpbb

**Version**

```
# docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker-compose version` (if applicable):
```
# docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by soldovskij** [comment]
Hi, yes, problem is here

**Comment by marcelothomaz** [comment]
Sorry, where Boris? I received just your message, no references

Regards
Em 9 de mai de 2019 19:47 -0300, Boris Soldovskij <notifications@github.com> escreveu:

Hi, yes, problem is here

**Comment by soldovskij** [comment]
![image](https://user-images.githubusercontent.com/7347880/57491672-5d8b1d80-72c6-11e9-9299-792bf0f6709e.png)

**Comment by soldovskij** [comment]
INCLUDEJS function set incorrect url.
'bitnami/phpbb' not needed

**Comment by javsalgar** [comment]
Hi,

Yes. I am afraid we still couldn't work on this task yet. I will update the thread as soon as we have more information.

**Comment by Sir-Ius** [comment]
Hi, this is still an issue for me. Is there a good way to work around this while this is not fixed?

**Comment by marcelothomaz** [comment]
Hi @Sir-Ius , not that I'm aware of.
@javsalgar is there anything I can do to help?

I tried to run through the code but it took me more time than I have.
Maybe with some guidance we can help?!

**Comment by tompizmor** [comment]
I believe this issue is caused by the persistence and relative symlinks. We are persisting the `styles` folder in `/bitnami/phpbb/styles` and it seems PhpBB is using the full path.

**Comment by wallforfry** [comment]
HI ! Something new about that ?

**Comment by javsalgar** [comment]
Hi,

I am afraid it is still in our backlog. We will update the issues when we have more news.

**Comment by penM000** [comment]
Hi.
Thank you for providing this wonderful image.
I have this problem too, but bitnami / phpbb also exists as a prefix in the newly added css and js by the following extensions.
https://example.com/bitnami/phpbb/ext/phpbb/collapsiblecategories/styles/all/theme/collapsiblecategories.css
The correct is as follows.
https://example.com/ext/phpbb/collapsiblecategories/styles/all/theme/collapsiblecategories.css

https://www.phpbb.com/customise/db/extension/collapsible_forum_categories/

**Comment by juan131** [comment]
Hi @penM000 

You're right, the issues with the CSS and JavaScript files hasn't been addressed yet. I'll try to prioritize it so we can have a solution for the PATH.

Thanks for your consideration and patience.

**Comment by maltokyo** [comment]
Hello is this now fixed? I don't understand the onhold status and what it means in this case.

**Comment by juan131** [comment]
Hi @maltokyo 

This issue hasn't been fixed yet. We're marking it as 'on-hold' since we have an internal task associated to this issue that hasn't been addressed.

We will update the issue when we have news.

**Comment by MasterMNB** [comment]
Hi,
i use a reverse proxy with nginx in front.
As workaround i added in nginx the rule `rewrite ^(.)(bitnami/phpbb/)(.) $1$3 break;` to correct the url.
Apache should also have such a function.

**Comment by juan131** [comment]
Hi @MasterMNB 

Thanks for sharing the solution you used on NGINX! It'll be very useful for our engineers once they target the associated task so it's fixed by default in the image.

In the meantime, it's possible to extend this image adding custom configuration to Apache as it's explained in the link below:

- https://github.com/bitnami/bitnami-docker-phpbb/#extend-this-image

**Comment by ibunjevac** [comment]
I solved the same problem by adding a line in my .htaccess file: 

`RewriteRule ^bitnami/phpbb/(.*)$ /$1 [L]`

maybe it helps someone.

**Comment by javsalgar** [comment]
Thanks!

**Comment by maltokyo** [comment]
@ibunjevac how did you add that, where?  I can't see any .htaccess files in my docker volume.

**Comment by ibunjevac** [comment]
@maltokyo  .htaccess file in my case was /opt/bitnami/apache/conf/vhosts/htaccess/phpbb-htaccess.conf.
But if you don't have it, you can create new file in root folder of your phpbb.

**Comment by maltokyo** [comment]
Thanks a lot!!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpbb#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
