### ISSUE TITLE
Username field not populating and can't "select all" etc

### ISSUE THREAD

**Issue by fredjohnston** [bitnami/bitnami-docker-phpbb#56]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by fredjohnston** [comment]
Example of problem... (see screenshot attached)...
ACP(AdminControlPanel)> General(tab)> ManageGroups> EG"RegisteredUsers","Members"> ...under "Add Users"... under Username:Field... click on [FindAMember] (underneath the Username: field)> ...new window pops up "Find a member"... MarkAll> (or even [Select] on single user, nothing gets selected, nothing gets populated into the "Username" field.  I would expect control to return back to the first window with the selected users then populated into the Username field.

![Screen Shot 2019-03-12 at 8 30 27 AM](https://user-images.githubusercontent.com/28265553/54200497-ea218700-44a1-11e9-8f87-9edc6f45ea7f.png)

**Comment by fredjohnston** [comment]
root@T-A:~# docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

root@T-A:~# docker info
Containers: 16
 Running: 10
 Paused: 0
 Stopped: 6
Images: 15
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 985.5MiB
Name: Toronto-A
ID: WTFK:VWLP:OE77:3VA4:YW37:QFUD:R5BW:MNGT:WLHH:AJNS:NYNW:3L4A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by fredjohnston** [comment]
root@T-A:/batch/PHPbb-TOP# cat docker-compose.yml 
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_phpbb
      - MARIADB_DATABASE=bitnami_phpbb
    volumes:
      - './mariadb_data:/bitnami'
    #restart: always
  phpbb:
    image: 'bitnami/phpbb:3'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=bn_phpbb
      - PHPBB_DATABASE_NAME=bitnami_phpbb
      - PHPBB_FORUM_NAME=Towns at Orchard Park
      - PHPBB_FORUM_DESCRIPTION=TOP Community Club
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '90:80'
      - '443:443'
    #restart: always
    volumes:
      - './phpbb_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phpbb_data:
    driver: local
root@T-A:/batch/PHPbb-TOP#

**Comment by andresbono** [comment]
Hi @fredjohnston, did you try to get in touch with phpBB support? I think this issue is related to the application itself not to the Bitnami Docker container. You can find their support channels here: https://www.phpbb.com/support/

**Comment by fredjohnston** [comment]
Thanks, i did think to do that, but it just seems so obvious of an issue, that i thought it may have more chance to be related to the docker instance... I'll try them too... thx
