### ISSUE TITLE
Client version 1.22 is too old

### ISSUE THREAD

**Issue by mylle** [bitnami/bitnami-docker-phpbb#60]
**Description**
I getting the following error when executing 'docker-compose up -d' on Windows Server 2016:
_ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version_

I've installed 'docker enterprise' and 'docker compose' on the windows 2016 server.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Enterprise
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9e27c76fe0
 Built:             10/17/2019 23:42:50
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9e27c76fe0
  Built:            10/17/2019 23:41:23
  OS/Arch:          windows/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.4
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.3204.amd64fre.rs1_release.190830-1500)
 Operating System: Windows Server 2016 Datacenter Version 1607 (OS Build 14393.3204)
 OSType: windows
 Architecture: x86_64
 CPUs: 1
 Total Memory: 8GiB
 Name: DKFTP
 ID: PRU6:5YST:4OSH:GJXO:FDRQ:H4BO:P6OM:DI3D:O3YT:B2HV:AUHO:I3MM
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Comment by dgomezleon** [comment]
Based on this [issue](https://github.com/docker/compose/issues/4106), you should edit your docker-compose.yml file, and change the first line to:

`version: '2.1'`

**Comment by mylle** [comment]
> l

When changing the version, I'm getting another error:
`Creating network "phpbb_default" with the default driver`
`ERROR: HNS failed with error : The parameter is incorrect.`

**Comment by dgomezleon** [comment]
Hello @mylle,

Sorry for the delay. This is a known issue. Windows systems only support one NAT network. Removing Netnat by invoke Remove-Netnat is not supported.

Run this command in powerhell.

> Get-NetNat | Remove-NetNat

I hope it helps.
