### ISSUE TITLE
Tabs not working for phpbb post page on fresh install

### ISSUE THREAD

**Issue by maltokyo** [bitnami/bitnami-docker-phpbb#61]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

When in the post page, the tabs below the post "Options" / "Attachments" / "Poll Creation" do not work as expected.  Instead of being able to click through the tabs and display their content, all tabs content is displayed right on the same page, and clicking the various tabs do nothing at all. See screenshot attached below.  This best shows what is happening.

**Steps to reproduce the issue:**

1. Fresh install of bitnami-phpbb (docker version)

**Describe the results you received:**

As above, clicking the various tabs do nothing at all.  Tab content is incorrectly displayed, tabs do not work.  See screenshot attached below.  This best shows what is happening.

**Describe the results you expected:**

Tabs work as in a standard phpbb installation

**Screenshot**
![bitnami-phpbb](https://user-images.githubusercontent.com/1388507/71733106-12231200-2e49-11ea-980d-71740dfa4af8.jpg)

**Version**

- Output of `docker version`:

docker version
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 10
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.42GiB
 Name: DELETED.DELETED.com
 ID: PWIB:EVGU:2WVK:P5GS:I24S:5772:Q2H3:DM5I:2MER:G6HT:YQIU:ARHC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on Debian Buster VPS (latest updates applied) 32GB RAM

**Comment by sameersbn** [comment]
@maltokyo thanks for bringing this to our attention. We will take a close look and try to fix this issue

**Comment by maltokyo** [comment]
Thank you. I tried a "standard install" (non docker) on the same server and
it didn't happen. So I guess it's caused by something in your docker
container. Let me know if I can test something or if you need further data
from me.

**Comment by sameersbn** [comment]
@maltokyo thank you for offering you help in tracking down the issue. We will keep you posted

**Comment by maltokyo** [comment]
Hello @sameersbn any updates on this?

**Comment by marcosbc** [comment]
Hi @maltokyo, we hadn't made any update until now. I took a quick look and found the issue, we'll look into implementing the fix but unfortunately cannot give you an ETA.

It can be workaround by adding the configuration below in `/opt/bitnami/apache/conf/vhosts/phpbb-vhost.conf` and `phpbb-https-vhost.conf`, right after the "ServerAlias *" line:

```

  Alias /bitnami/phpbb /bitnami/phpbb
  <Directory "/bitnami/phpbb">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php
  </Directory>
```

It is happening because the upstream application is resolving the absolute path for symlinked files, meaning it would resolve `/opt/bitnami/phpbb/.../forum_fn.js` to `/bitnami/phpbb/.../forum_fn.js`, with this second path not being accessible via the Apache web server.

The ideal fix would be for the application not to resolve the absolute path in that way, as it is supposing that the web server will be able to resolve it. Therefore it's an upstream issue, and even reported the fix could take some to get implemented.

In the meantime, while we implement the fix/workaround, you could try and mount both `phpbb-vhost.conf` and `phpbb-https-vhost.conf` via docker-compose, which should do the trick for you.

We will let you know if we have any update regarding the implementation.

**Comment by maltokyo** [comment]
Thank you. This is very helpful. I appreciate it.

**Comment by maltokyo** [comment]
Hello @marcosbc thank you for your help, unfortunately this didnt work.

I now get this when starting the container.

```
kagi_mariadb       | Version: '10.3.22-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
kagi_phpbb         | nami    INFO  Initializing phpbb
kagi_phpbb         | Error executing 'postInstallation': Unable to start com.bitnami.apache: httpd: Syntax error on line 517 of /opt/bitnami/apache/conf/httpd.conf: Syntax error on line 28 of /opt/bitnami/apache/conf/vhosts/phpbb-https-vhost.conf: Could not open configuration file /opt/bitnami/apache/conf/vhosts/htaccess/phpbb-htaccess.conf: No such file or directory
kagi_phpbb         | : httpd: Syntax error on line 517 of /opt/bitnami/apache/conf/httpd.conf: Syntax error on line 28 of /opt/bitnami/apache/conf/vhosts/phpbb-https-vhost.conf: Could not open configuration file /opt/bitnami/apache/conf/vhosts/htaccess/phpbb-htaccess.conf: No such file or directory
kagi_phpbb         | 
```

Here is the content now of both files, replaced via docker-compose volume.  Could you please confirm that this is correct, is it ok that alias has `Alias` has `/bitnami/phpbb /bitnami/phpbb` twice?

**phpbb-https-vhost.conf:**
```
AddType application/x-httpd-php .php

<VirtualHost  127.0.0.1:443  _default_:443>
  ServerAlias *

# start fixing this: https://github.com/bitnami/bitnami-docker-phpbb/issues/61
  Alias /bitnami/phpbb /bitnami/phpbb
  <Directory "/bitnami/phpbb">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php
  </Directory>
# end fixing this: https://github.com/bitnami/bitnami-docker-phpbb/issues/61

  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  DocumentRoot /opt/bitnami/phpbb
  <Directory "/opt/bitnami/phpbb">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php
    
    
  </Directory>
  Include /opt/bitnami/apache/conf/vhosts/htaccess/phpbb-htaccess.conf
</VirtualHost>

```

**and phpbb-vhost.conf:**
```
AddType application/x-httpd-php .php

<VirtualHost  127.0.0.1:80  _default_:80>
  ServerAlias *


# start fixing this: https://github.com/bitnami/bitnami-docker-phpbb/issues/61
  Alias /bitnami/phpbb /bitnami/phpbb
  <Directory "/bitnami/phpbb">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php
  </Directory>
# end fixing this: https://github.com/bitnami/bitnami-docker-phpbb/issues/61

  
  DocumentRoot /opt/bitnami/phpbb
  <Directory "/opt/bitnami/phpbb">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php
    
    
  </Directory>
  Include /opt/bitnami/apache/conf/vhosts/htaccess/phpbb-htaccess.conf
</VirtualHost>
```

**Comment by marcosbc** [comment]
@maltokyo You should be able to apply the changes by mounting a script to `/docker-entrypoint-init.d` and then reload the Apache configuration.

In any case, we just wanted to let you know that we are working on implementing this change onto the Bitnami phpBB docker images. Hopefully it will be available with the fix later today or tomorrow morning. We'll keep you posted.

**Comment by marcosbc** [comment]
@maltokyo Just wanted to let you know that we released phpBB `3.3.0-debian-10-r72` which includes the fix mentioned in this topic. I tested it works properly, so I'm closing this issue. However, if you continue finding the issue please let us know.

**Comment by maltokyo** [comment]
Thank you!! Great!!

**Comment by maltokyo** [comment]
Works well as expected, thanks again!

**Comment by marcosbc** [comment]
Great to hear! Thank you for the fast response!
