### ISSUE TITLE
Feature Request: PHPBB_DATABASE_PREFIX variable

### ISSUE THREAD

**Issue by mink-r** [bitnami/bitnami-docker-phpbb#63]
**Description**

As an existing phpBB forum administrator, I want to migrate my existing install to a bitnami Docker instance. My existing install h as a custom $table_prefix variable in config.php

**Steps to reproduce the issue:**

1. Note there is no PHPBB_DATABASE_PREFIX variable documented

**Describe the results you received:**

- container ignores existing data

**Describe the results you expected:**

- PHPBB_DATABASE_PREFIX would account for alternative db prefixes

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:32 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:38:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.0.0-38-generic
Operating System: Ubuntu 19.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.693GiB
Name: docker
ID: LWS7:L6Y6:F5S3:YOG7:M22A:HM4V:7IMK:DSS2:UYGH:MZER:NWGW:ICF5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1b  26 Feb 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
N/A

**Comment by andresbono** [comment]
Hi @mink-rizon, thanks for opening this issue.

We will work on including this feature and we will keep this thread updated with any news we may have.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpbb#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
