### ISSUE TITLE
When installing phpBB default it cannot connect to mariadb database

### ISSUE THREAD

**Issue by rene-72** [bitnami/bitnami-docker-phpbb#66]
When installing phpBB default it cannot connect to database maria db

I have tryed the following.
Installing with https://github.com/bitnami/bitnami-docker-phpbb/blob/master/docker-compose.yml

An app is build mariadb starts up and ready phpbb container doesnot work only text is log file EOF and container shutdown

When installing manual I get the maria & phpbb running only the phpbb cannot connect to database server.
I did install it with option empty password enabled yes eand anothertime empty password no and added password option but no success.

I did install the latest version.

Best regards,
Rene

**Comment by unraid-zeuzs** [comment]
Same Problem after Update phpbb on Unraid System. Even after reinstalling the same error.

[38;5;6mphpbb [38;5;5m12:06:58.53 [0m[38;5;2mINFO [0m ==> ** Starting phpBB setup **
[38;5;6mphpbb [38;5;5m12:06:58.54 [0m[38;5;2mINFO [0m ==> Configuring PHP options
[38;5;6mphpbb [38;5;5m12:06:58.54 [0m[38;5;2mINFO [0m ==> Setting PHP memory_limit option
[38;5;6mphpbb [38;5;5m12:06:58.56 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_CLIENT_* env vars
[38;5;6mphpbb [38;5;5m12:06:58.59 [0m[38;5;2mINFO [0m ==> Ensuring phpBB directories exist
[38;5;6mphpbb [38;5;5m12:06:58.60 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
[38;5;6mphpbb [38;5;5m12:07:58.76 [0m[38;5;1mERROR[0m ==> Could not connect to the database

mariadb and phpmyadmin work without problems

Kind regards

Sascha

**Comment by FraPazGal** [comment]
Hello @rene-72 @unraid-zeuzs,

I'm having problems to reproduce your issue. Just doing a `docker-compose up` with the provided [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-phpbb/blob/master/docker-compose.yml) doesn't output any errors on my side. 

Could you attach any configuration changes to the `docker-compose.yaml`, if any? Also, is it a fresh installation or does it reuse volumes from a previous installation?

**Comment by rene-72** [comment]
I got issues with the yaml version thats on dockerhub aswell as the manual script.
New install or reinstall both fail

**Comment by unraid-zeuzs** [comment]
after install Version bitnami/phpbb:3.3.1-debian-10-r26 it will work. installing the current version fails wtih no connect to the database

**Comment by dani8art** [comment]
Hi @rene-72 have you tested to start a new deployment from scratch? sometimes volumes and data can be corrupted and could make conflict with the data in the current environment. Could you try these commands?

```console
$ docker-compose down -v
$ docker-compose up -d
```

You can try to remove the old volumes with the old data before deploying a new instance.

**Comment by FraPazGal** [comment]
Hi @rene-72,

Did your container start after removing the old volumes? Regarding the use of a specific image version, you would need to edit the `docker-compose.yaml` with the following:

```yaml
  phpbb:
    image: 'docker.io/bitnami/phpbb:3.3.1-debian-10-rXX'
```
