### ISSUE TITLE
phpBB failed to install

### ISSUE THREAD

**Issue by roman-vancura** [bitnami/bitnami-docker-phpbb#69]
**Description**

Hello,
I try to run [bitnami/phpb:latest](https://registry.hub.docker.com/r/bitnami/phpbb/) container on my Synology NAS ([DS218+](https://www.synology.com/en-global/products/DS218)). 
However the installation is always corrupted. 

The web page after fresh installation always starts with some PHP warning: 
![corrupted](https://user-images.githubusercontent.com/17555409/103335295-d8ddac00-4a74-11eb-97f3-62133938ca22.PNG)

And the container log says **phpBB failed to install**: 
![log](https://user-images.githubusercontent.com/17555409/103334935-a5e6e880-4a73-11eb-83c7-10dbbfaa4554.PNG)

**Version**

- Output of `docker version`:

```
root@DSM_Brno:~# docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       3a371f3
  Built:            Fri Mar 13 06:44:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
root@DSM_Brno:~# docker info
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 18.09.8
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 0cf16177dbb234350dc27dd2bbd1d7cebd098108
runc version: 6cc9d3f2cd512eeb3d548e2f6b75bcdebc779d4d
init version: e01de58 (expected: fec3683)
Security Options:
 apparmor
Kernel Version: 4.4.59+
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 9.577GiB
Name: DSM_Brno
ID: BA2F:UV2U:B4JD:OT56:AAJG:MWW2:EMA6:OMG3:T5JN:C6TR:U36F:3SKW
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

- Synology container settings (json file):

```
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "/opt/bitnami/scripts/apache/run.sh",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "entrypoint_default" : "/opt/bitnami/scripts/phpbb/entrypoint.sh",
   "env_variables" : [
      {
         "key" : "PHPBB_DATABASE_PASSWORD",
         "value" : "123456"
      },
      {
         "key" : "PHPBB_DATABASE_USER",
         "value" : "bn_phpbb"
      },
      {
         "key" : "PHPBB_DATABASE_NAME",
         "value" : "bitnami_phpbb"
      },
      {
         "key" : "PHPBB_DATABASE_HOST",
         "value" : "mariadb3"
      },
      {
         "key" : "PATH",
         "value" : "/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/apache/bin:/opt/bitnami/mysql/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "HOME",
         "value" : "/"
      },
      {
         "key" : "OS_ARCH",
         "value" : "amd64"
      },
      {
         "key" : "OS_FLAVOUR",
         "value" : "debian-10"
      },
      {
         "key" : "OS_NAME",
         "value" : "linux"
      },
      {
         "key" : "ALLOW_EMPTY_PASSWORD",
         "value" : "no"
      },
      {
         "key" : "APACHE_ENABLE_CUSTOM_PORTS",
         "value" : "no"
      },
      {
         "key" : "APACHE_HTTPS_PORT_NUMBER",
         "value" : ""
      },
      {
         "key" : "APACHE_HTTP_PORT_NUMBER",
         "value" : ""
      },
      {
         "key" : "BITNAMI_APP_NAME",
         "value" : "phpbb"
      },
      {
         "key" : "BITNAMI_IMAGE_VERSION",
         "value" : "3.3.2-debian-10-r48"
      },
      {
         "key" : "MARIADB_HOST",
         "value" : "mariadb"
      },
      {
         "key" : "MARIADB_PORT_NUMBER",
         "value" : "3306"
      },
      {
         "key" : "MARIADB_ROOT_PASSWORD",
         "value" : ""
      },
      {
         "key" : "MARIADB_ROOT_USER",
         "value" : "root"
      },
      {
         "key" : "MYSQL_CLIENT_CREATE_DATABASE_NAME",
         "value" : ""
      },
      {
         "key" : "MYSQL_CLIENT_CREATE_DATABASE_PASSWORD",
         "value" : ""
      },
      {
         "key" : "MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES",
         "value" : "ALL"
      },
      {
         "key" : "MYSQL_CLIENT_CREATE_DATABASE_USER",
         "value" : ""
      },
      {
         "key" : "MYSQL_CLIENT_ENABLE_SSL",
         "value" : "no"
      },
      {
         "key" : "MYSQL_CLIENT_SSL_CA_FILE",
         "value" : ""
      }
   ],
   "exporting" : false,
   "id" : "10784b8d25c319bd22fad047494dc518d1b1820203853d86a0abdb3f801a7879",
   "image" : "bitnami/phpbb:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "bitnami-phpbb3",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      },
      {
         "driver" : "bridge",
         "name" : "phpbb-network"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8080,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 8443,
         "host_port" : 0,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : []
}

```

- Container log:
[log.zip](https://github.com/bitnami/bitnami-docker-phpbb/files/5753263/log.zip)

**Additional Information:**
When I replace the `/opt/bitnami/scripts/apache/run.sh` execution command by `httpd -f /opt/bitnami/apache/conf/httpd.conf -DFOREGROUND`, I can follow the phpBB setup wizard without any issue.

**Comment by rafariossaa** [comment]
Hi,
  It is failing in the `phpbb/setup.sh` script, if you take a look to the `/opt/bitnami/scripts/phpbb/entrypoint.sh` script, you will see there are several initialization scripts called there. If you use other CMD, it will not run the initialization scripts and it will not configure the web server and phpbb.
  Could you try to enable debug by setting `BITNAMI_DEBUG=true` ? That should provide more information.

**Comment by roman-vancura** [comment]
Thanks @rafariossaa for hint.

here is my log with `BITNAMI_DEBUG=true`:
![log-debug](https://user-images.githubusercontent.com/17555409/103397624-6a165680-4b39-11eb-93c1-7bd929ff8b05.PNG)

and the complete log:
[bitnami-phpbb3-debug.zip](https://github.com/bitnami/bitnami-docker-phpbb/files/5756601/bitnami-phpbb3-debug.zip)

**Comment by rafariossaa** [comment]
Hi, 
 Not 100% sure, but it seems it could be due a timeout [here](https://github.com/bitnami/bitnami-docker-phpbb/blob/ff0504141a7032157c82383c502d3355a1a19fd1/3/debian-10/rootfs/opt/bitnami/scripts/libphpbb.sh#L311) because of the use of [`retry_while`](https://github.com/bitnami/bitnami-docker-phpbb/blob/ff0504141a7032157c82383c502d3355a1a19fd1/3/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh#L210) . 
 I am creating an internal task to improve this, but right now the only solution it to change the values in `libos.sh` and build the image by yourself.
 You will need to change the value in [3/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh](https://github.com/bitnami/bitnami-docker-phpbb/blob/ff0504141a7032157c82383c502d3355a1a19fd1/3/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh#L212), maybe by something like:
```
    local retries="${2:-24}"
```
  This would give it 24 retries times 5 seconds (sleep_time) = 10 minutes to initialize.
  Could you give it a try ?

**Comment by roman-vancura** [comment]
Thanks @rafariossaa  for your reply,
I have modified `/opt/bitnami/scripts/libos.sh` as proposed and the phpBB was installed succesfully: 
![log-10min](https://user-images.githubusercontent.com/17555409/103423135-51dc2100-4ba5-11eb-9534-3f2d2a42259d.PNG)
The phpBB installation took ~6 minutes.
Complete log:
[bitnami-phpbb3-10min.zip](https://github.com/bitnami/bitnami-docker-phpbb/files/5758120/bitnami-phpbb3-10min.zip)

Thanks once again, you are great.
