### ISSUE TITLE
Pretty URLS / mod_rewrite does not seem to work

### ISSUE THREAD

**Issue by Beenhakker** [bitnami/bitnami-docker-phpbb#70]
**Description**

Pretty URL's e.g. mod_rewrite not working? 

We have enabled rewrites in the admin interface, but does not seem to work.

I have logged into the container, checked to see that the modules are loaded, 
which htaccess config is active (https://docs.bitnami.com/bch/apps/phpbb/administration/use-htaccess/)

**Steps to reproduce the issue:**

1. Fire up container
2. Log in as admin user
3. Enable pretty urls

**Describe the results you received:**

Pretty URL's should be active

URL's are not rewritten

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-13-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.3GiB
 Name: app-01
 ID: ATCI:J3GA:2WNG:U3HN:XZXY:MM6K:ESHM:TMS5:R2YW:INBK:64ON:KDVC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi, 
  Those instructions are for the cloud image.
  Could you indicate what have you tried so far ?. Which is you .htaccess ? Do you have problems enabling the pretty urls or it is with the rewrites ? How are you enabling pretty urls in phpbb ?

**Comment by Beenhakker** [comment]
Hi,

Thanks for your reply.

We simply have tried to enable the pretty URL's in the PHPBB admin interface (button), and sticked with the default rewrites that are enabled in the container - which should suffice - so we have not used any additional .htaccess files.

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure of the option you are using. It is working when I use this one:
![option](https://user-images.githubusercontent.com/11049367/104570569-6531c680-5652-11eb-8129-809d15b18e88.png)
  When disabled you get the `app.php` string in the url:
![disabled](https://user-images.githubusercontent.com/11049367/104570769-a033fa00-5652-11eb-83fd-afc6731bf2a8.png)
  If you enable the option, that part disappears:
![enabled](https://user-images.githubusercontent.com/11049367/104570898-be015f00-5652-11eb-83e7-abf9a8d428fe.png)

**Comment by Beenhakker** [comment]
Hi,

Thanks for you quick reply and screenshots.

We have used the same setting, but it does not work. 

Why it does not work, is because in our application, index.php is used instead of app.php, for unknown reasons.
All the rewrite rules are based on app.php, hence the reason it is not working for us. 

Do you have an idea why our container uses index.php instead of app.php?

**Comment by rafariossaa** [comment]
Hi,
  To be honest, I don't know.
  Could you indicate me which image are you using ? Maybe is an issue in a specific image release. 
  Also, I am supposing that you are using our image without any other modification, if not, maybe you can start reviewing your changes to try to figure out what is causing this issue.

**Comment by Beenhakker** [comment]
We are using image: bitnami/phpbb:3.3.2.

We have not any changes. We did move from an on premise installation to this container, and have only copied the leftover asset directories to a docker volume.

**Comment by rafariossaa** [comment]
Hi @Beenhakker ,
  Do you know which release of `3.3.2` ? Did you also migrate your database ? I am not sure if this can be related also to database information.
  In any case, my advise is to ask also in phpbb forums, maybe they can shed some light on this kind of issues.
