### ISSUE TITLE
Real ip behind nginx proxy

### ISSUE THREAD

**Issue by Zwixx** [bitnami/bitnami-docker-phpbb#71]
**Description**

Behind a nginx-proxy not the IP of the real user, instead 127.0.0.2 is used for example

**Steps to reproduce the issue:**

I use a nginx-proxy and configured the following header lines in the proxy-config:

    proxy_pass              http://phpbb:8080;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        Host $http_host;
    proxy_set_header        X-Forwarded-Proto $scheme;

**Describe the results you received:**

Not the real IP, the internal IP is logged.

**Describe the results you expected:**

The real IP is logged and showed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Is there a workaround or configuration so phpbb uses the real ip adress?

**Version**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Comment by Mauraza** [comment]
Hi @Zwixx,

the normal result is not appears the real IP, you need to configure Nginx to get the real IP.
Could you check the documentation of Nginx http://nginx.org/en/docs/http/ngx_http_realip_module.html?

**Comment by Zwixx** [comment]
If I understand correctly, I have to set these directives in the container of bitnami/phpbb, that I trust this nginx to send the correct IP?

And there is no config option to modify this in bitnami/phpbb. So I must create a custom container?

**Comment by Mauraza** [comment]
Hi @Zwixx,

No, you need to change the configuration of Nginx. You can do something similar to this page https://www.cyberciti.biz/faq/linux-unix-nginx-access-file-log-real-ip-address-of-visitor/  or something like appears in https://stackoverflow.com/questions/30943112/get-ip-user-with-nginx-and-node

**Comment by Zwixx** [comment]
It not worked for me. I look into it a little bit more. Like all documentation the destination server must trust the IP that's sends the header. And in my solution this is the phpbb

**Comment by Mauraza** [comment]
Hi @Zwixx,

did you finally solve the issue?

**Comment by Zwixx** [comment]
No, I ignore the problem for now and log the access to the phpbb in the nginx

**Comment by Mauraza** [comment]
Hi @Zwixx,

Did you try something like this https://www.cyberciti.biz/faq/nginx-restore-real-ip-address-when-behind-a-reverse-proxy/?
