### ISSUE TITLE
Does not work on xfs ftype=0 docker filesystem

### ISSUE THREAD

**Issue by rokx** [bitnami/bitnami-docker-phpbb#72]
**Description**

phpbb container dose not run if filestorage system of docker is overlay and ftype=0 (docker info -> d_type: false)

Relevant docker info excerpt

Storage Driver: overlay
  Backing Filesystem: xfs
  Supports d_type: false

...
phpbb 07:16:43.50 INFO  ==> Running installation wizard
phpbb 07:16:54.84 INFO  ==> phpBB installed successfully
phpbb 07:16:54.85 INFO  ==> Stopping apache
phpbb 07:16:55.91 INFO  ==> apache stopped
phpbb 07:16:55.91 INFO  ==> Persisting phpBB installation
rm: cannot remove '/opt/bitnami/phpbb/store': Directory not empty

**Steps to reproduce the issue:**

1. Have docker running on storage driver overlay, backing filesystem xfs and d_type:false 
2. run docker-compose up with the yml file from this repository

**Describe the results you received:**

phpbb container starts, installs phpbb,  but fails in the stage of persisting data and  stops

**Describe the results you expected:**

Running phpbb container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Running on storage driver overlay2 and ftype=1 has no issues.

Maybe a check of storage driver or some other information to let the user know what went wrong would be appropriate. Or update the readme prerequisites to ensure docker has correct storage.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 8
  Paused: 0
  Stopped: 5
 Images: 43
 Server Version: 19.03.2
 Storage Driver: overlay
  Backing Filesystem: xfs
  Supports d_type: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.25.1.el7.x86_64
 Operating System: Red Hat Enterprise Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.638GiB
 Name:   hidden
 ID: U2SP:VDAI:M6XM:MWCU:4SWR:BMHT:GHO7:FO2Y:TMPO:4AUQ:S5OL:4ZMR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: the overlay storage-driver is deprecated, and will be removed in a future release.
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

```

**Comment by javsalgar** [comment]
Hi,

Could you provide more context about the needs of that filesystem settings? Our tests use the default docker configuration. It seems that the settings you are using are deprecated by Docker, what's the reason for using them?

**Comment by rokx** [comment]
I had a running instance with the overlay storage driver. I did not see any warning that this storage driver was deprecated. Only that the storage driver might be removed in a future release.

I could not explain to myself for some time why the installation fails with this error. It took me quite a while to find out that the storage driver was the fault.

This issue issues is just for a reminder or to add to troubleshooting section a possible cause of failed installation.

My docker instance was upgraded a few times. Maybe the overlay driver was the default back then.

**Comment by javsalgar** [comment]
So, do you think it could be helpful to add a storage troubleshooting section in our documentation? I could let the docs team know this feedback

**Comment by rokx** [comment]
At least there is an issue someone can find someday. I'm happy with that.
