### ISSUE TITLE
Moving a existing PhpBB site to Docker

### ISSUE THREAD

**Issue by Tarbetu** [bitnami/bitnami-docker-phpbb#75]
Hi.

I just wanted to move my PhpBB installation to Docker. There is an example for Wordpress.

https://stephenafamo.com/blog/posts/moving-a-wordpress-site-into-a-docker-container#step-7-fix-wp-configphp

Is it possible for PhpBB or should I work on a new install?

Thanks. :)

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpbb#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
