### ISSUE TITLE
Error at the Upload Path

### ISSUE THREAD

**Issue by robertatc** [bitnami/bitnami-docker-phpbb#76]
### Name and Version

bitnami version 3.3.5

### What steps will reproduce the bug?

I want to change the upload path for the attachments, and all the time it gives me an error that the path doesn't exist. 

### What do you see instead?

Nothing, as the error persit.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpbb#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
