### ISSUE TITLE
Support docker secrets

### ISSUE THREAD

**Issue by mrnbrkt** [bitnami/bitnami-docker-phpbb#77]
### Name and Version

bitnami/phpbb:3

### What is the problem this feature will solve?

Currently, there's no option to use docker secrets for serving the database username, passwords, etc. to the container. Only to save the password in the environment vars, which is not the right way to do it in a swarm. 

(This is an issue that's open in multiple bitnami images…)

### What is the feature you are proposing to solve the problem?

Support Docker Secrets, much like https://github.com/bitnami/bitnami-docker-mysql/issues/44 https://github.com/bitnami/bitnami-docker-postgresql/issues/195

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpbb#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by mrnbrkt** [comment]
Looks like it's not documented but IS supported. Yay!
