### ISSUE TITLE
/opt/bitnami/scripts/libphpbb.sh: line 179: PHPBB_SMTP_PORT: unbound variable

### ISSUE THREAD

**Issue by smh2022** [bitnami/bitnami-docker-phpbb#78]
### Name and Version

bitnami-docker-phpbb/blob/3.3.7-debian-11-r5

### What steps will reproduce the bug?

install phpbb with 

App Version: 3.3.7
Package Version: 12.2.9

phpbb failed to started because of:

`
phpbb 17:31:04.82 Welcome to the Bitnami phpbb container
phpbb 17:31:04.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phpbb
phpbb 17:31:04.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phpbb/issues
phpbb 17:31:04.82
phpbb 17:31:04.82 INFO  ==> ** Starting phpBB setup **
realpath: /bitnami/apache/conf: No such file or directory
phpbb 17:31:04.86 INFO  ==> Configuring the HTTP port
phpbb 17:31:04.87 INFO  ==> Configuring the HTTPS port
phpbb 17:31:04.87 INFO  ==> Configuring Apache ServerTokens directive
phpbb 17:31:04.89 INFO  ==> Configuring PHP options
phpbb 17:31:04.90 INFO  ==> Setting PHP expose_php option
phpbb 17:31:04.92 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
phpbb 17:31:05.00 INFO  ==> Ensuring phpBB directories exist
phpbb 17:31:05.01 INFO  ==> Trying to connect to the database server
phpbb 17:31:05.04 INFO  ==> Creating configuration file for installation
phpbb 17:31:05.86 INFO  ==> Configuring SMTP credentials
/opt/bitnami/scripts/libphpbb.sh: line 179: PHPBB_SMTP_PORT: unbound variable
`

### What is the expected behavior?

phpbb starts without problem

### What do you see instead?

/opt/bitnami/scripts/libphpbb.sh: line 179: PHPBB_SMTP_PORT: unbound variable

### Additional information

https://github.com/bitnami/bitnami-docker-phpbb/blob/3.3.7-debian-11-r5/3/debian-10/rootfs/opt/bitnami/scripts/libphpbb.sh#L179

it should be

`
            phpbb_set_installer_config "smtp_port" "$PHPBB_SMTP_PORT_NUMBER" "int"
`

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpbb#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
